### PR TITLE
refactor: switch postgres to trust mode eliminating env vars

### PR DESCRIPTION
**Pull request by Fogapod**
Application can still be configured using old variables to use remote database, but local postgres in compose file no longer needs configuration.

This is a breaking change because you will either need to reset existing database or change access control to trust mode yourself (restart seem to not be working), local .env file will also need to be cleaned from postgres variables.

### CODE REVIEW

**Comment by corp-0** [comment]
what is this trusted mode?

**Comment by Fogapod** [comment]
You don't need password, since postgres is isolated in docker container only app has access to it. The only exception is dev-compose file, but just don't run it on prod and it's fine

**Comment by corp-0** [comment]
alrighty then. Keep in mind that ``breaking`` will bump the semver one major. I'd go with refactor instead, we know we need to flush the db and do it again, not a big deal at this point.

**Comment by Fogapod** [comment]
Alright

**Pull request merged**
