### PR TITLE
refactor(gha): lint PRs, deploy on merges

### PR DESCRIPTION
**Pull request by Fogapod**
Actions are separated into 3 files to simplify workflows, added a few
more steps (lint, building docker image)

### CODE REVIEW

**Comment by Fogapod** [comment]
Not yet sure why docker build cache does not work

**Comment by Fogapod** [comment]
Probably needs a bit more debugging. Please don't merge yet

**Comment by corp-0** [comment]
let me know when you're done

**Comment by Fogapod** [comment]
I think this is ready @corp-0

**Pull request merged**
